name: Build and Push

on:
  push:
    branches:
      - main

jobs:

  build_and_push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@3

      - name: Setup Python 3.12
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      - name: Build the image using Dockerfile
        env:
          GITHUB_SHA: ${{ github.sha }}
          DOCKER_IMAGE_NAME: argocd-python-app
        run: |
          docker image build . --file Dockerfile --tag $DOCKER_IMAGE_NAME:$GITHUB_SHA

      - name: Push the image to container registry
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: |
          docker image tag $DOCKER_IMAGE_NAME:$GITHUB_SHA $DOCKER_USERNAME/$DOCKER_IMAGE_NAME:$GITHUB_SHA
          docker image push $DOCKER_USERNAME/$DOCKER_IMAGE_NAME:$GITHUB_SHA
