name: Build and Push

on:
  # push:
  #   branches:
  #     - main

  workflow_dispatch:

jobs:

  build_and_push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Python 3.12.0
        uses: actions/setup-python@v4
        with:
          python-version: "3.12.0"

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push the image
        env:
          GITHUB_SHA: ${{ github.sha }}
          DOCKER_USERNAME: ${{ vars.DOCKER_USERNAME }}
          DOCKER_IMAGE_NAME: ${{ vars.DOCKER_IMAGE_NAME }}
        run: |
          docker image build . --file Dockerfile --tag $DOCKER_IMAGE_NAME:$GITHUB_SHA
          docker image tag $DOCKER_IMAGE_NAME:$GITHUB_SHA $DOCKER_USERNAME/$DOCKER_IMAGE_NAME:$GITHUB_SHA
          docker image push $DOCKER_USERNAME/$DOCKER_IMAGE_NAME:$GITHUB_SHA
